# Generated by Django 5.2.8 on 2025-11-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('current_position', models.CharField(blank=True, max_length=200, null=True)),
                ('years_experience', models.IntegerField(default=0)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Application Received'), ('screening', 'Under Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='received', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'ordering': ['-created_at'],
            },
        ),
    ]
