# Generated by Django 5.2.8 on 2025-11-29 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_jobposting_alter_workflowevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='application_source',
            field=models.CharField(blank=True, choices=[('website', 'Company Website'), ('linkedin', 'LinkedIn'), ('referral', 'Employee Referral'), ('job_board', 'Job Board'), ('direct', 'Direct Application'), ('other', 'Other')], default='direct', max_length=100),
        ),
    ]
