# Generated by Django 5.2.8 on 2025-12-04 12:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_candidate_application_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_type', models.CharField(choices=[('IF_SENIOR', 'Islamic Finance Professional (Senior)'), ('IF_JUNIOR', 'Islamic Finance Analyst (Entry-Level)'), ('TECH_DEV', 'Technology/Software Developer'), ('TECH_ANALYST', 'Data/Business Analyst'), ('HR_MANAGER', 'HR Manager'), ('ADMIN', 'Administrative/Support Staff'), ('EXEC_SENIOR', 'Senior Executive'), ('ENTRY_LEVEL', 'Entry-Level (General)'), ('CUSTOM', 'Custom Profile')], max_length=20)),
                ('description', models.TextField()),
                ('education_weight', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('experience_weight', models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('skills_weight', models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('islamic_finance_weight', models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_default', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Job Role Profile',
                'verbose_name_plural': 'Job Role Profiles',
                'ordering': ['profile_type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='jobposting',
            name='role_profile',
            field=models.ForeignKey(blank=True, help_text='Select a pre-configured role profile (weights can still be customized)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.jobroleprofile'),
        ),
    ]
