# Generated by Django 5.2.8 on 2025-12-11 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_jobroleprofile_jobposting_role_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('programming_language', 'Programming Language'), ('framework', 'Framework'), ('database', 'Database'), ('cloud_service', 'Cloud Service'), ('tool', 'Tool'), ('protocol', 'Protocol'), ('methodology', 'Methodology'), ('finance_concept', 'Finance Concept'), ('islamic_finance_term', 'Islamic Finance Term'), ('soft_skill', 'Soft Skill'), ('certification', 'Certification'), ('domain_knowledge', 'Domain Knowledge')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Skill Type',
                'verbose_name_plural': 'Skill Types',
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='recruitment.skillcategory')),
            ],
            options={
                'verbose_name': 'Skill Category',
                'verbose_name_plural': 'Skill Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SkillDefinition',
            fields=[
                ('skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('canonical_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_hard_skill', models.BooleanField(default=True)),
                ('importance_weight', models.FloatField(default=1.0)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recruitment.skillcategory')),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_skills', to='recruitment.skilldefinition')),
                ('related_skills', models.ManyToManyField(blank=True, to='recruitment.skilldefinition')),
                ('skill_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.skilltype')),
            ],
            options={
                'verbose_name': 'Skill Definition',
                'verbose_name_plural': 'Skill Definitions',
                'ordering': ['canonical_name'],
            },
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(db_index=True, max_length=200)),
                ('normalized_text', models.CharField(db_index=True, max_length=200)),
                ('priority', models.IntegerField(default=1)),
                ('is_exact_match', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='recruitment.skilldefinition')),
            ],
            options={
                'verbose_name': 'Skill Alias',
                'verbose_name_plural': 'Skill Aliases',
                'indexes': [models.Index(fields=['normalized_text'], name='recruitment_normali_0b7b6d_idx')],
                'unique_together': {('skill', 'normalized_text')},
            },
        ),
        migrations.CreateModel(
            name='ExtractedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(choices=[('skills', 'Skills Section'), ('experience', 'Work Experience'), ('education', 'Education'), ('certifications', 'Certifications'), ('projects', 'Projects'), ('other', 'Other')], max_length=50)),
                ('frequency', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('matched_via', models.CharField(choices=[('exact', 'Exact Match'), ('alias', 'Alias Match'), ('fuzzy', 'Fuzzy Match'), ('nlp', 'NLP Extraction')], default='exact', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='recruitment.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.skilldefinition')),
            ],
            options={
                'verbose_name': 'Extracted Skill',
                'verbose_name_plural': 'Extracted Skills',
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.AddIndex(
            model_name='skilldefinition',
            index=models.Index(fields=['canonical_name'], name='recruitment_canonic_8594a3_idx'),
        ),
        migrations.AddIndex(
            model_name='skilldefinition',
            index=models.Index(fields=['category', 'is_active'], name='recruitment_categor_065298_idx'),
        ),
    ]
