# Generated by Django 5.2.8 on 2025-12-12 22:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_skilltype_skillcategory_skilldefinition_skillalias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='role_profile',
        ),
        migrations.AlterUniqueTogether(
            name='skillalias',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skillalias',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='skilldefinition',
            name='category',
        ),
        migrations.RemoveField(
            model_name='skilldefinition',
            name='parent_skill',
        ),
        migrations.RemoveField(
            model_name='skilldefinition',
            name='related_skills',
        ),
        migrations.RemoveField(
            model_name='skilldefinition',
            name='skill_type',
        ),
        migrations.AddField(
            model_name='candidate',
            name='ats_issues',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ats_readability_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AddField(
            model_name='skill',
            name='esco_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='source',
            field=models.CharField(choices=[('regex', 'REGEX Pattern'), ('esco', 'ESCO Database'), ('manual', 'Manually Added'), ('extracted', 'Text Extraction')], default='extracted', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('finance', 'Finance'), ('islamic_finance', 'Islamic Finance'), ('soft_skill', 'Soft Skill'), ('language', 'Language'), ('other', 'Other')], default='technical', max_length=20),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill_name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='ExtractedSkill',
        ),
        migrations.DeleteModel(
            name='JobRoleProfile',
        ),
        migrations.DeleteModel(
            name='SkillAlias',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
        migrations.DeleteModel(
            name='SkillDefinition',
        ),
        migrations.DeleteModel(
            name='SkillType',
        ),
    ]
