# Generated by Django 5.2.8 on 2025-12-13 03:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_remove_jobposting_role_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_experience', models.IntegerField(default=0)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidatejobapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='ats_issues',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='ats_readability_score',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='years_experience',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='islamic_finance_weight',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='max_years_experience',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='min_education_level',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='min_years_experience',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='required_certifications',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='special_requirements',
        ),
        migrations.RemoveField(
            model_name='score',
            name='evaluated_at',
        ),
        migrations.RemoveField(
            model_name='score',
            name='rank',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='domain_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AddField(
            model_name='score',
            name='calculated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_source',
            field=models.CharField(choices=[('website', 'Company Website'), ('linkedin', 'LinkedIn'), ('referral', 'Employee Referral'), ('job_board', 'Job Board'), ('direct', 'Direct Application'), ('other', 'Other')], default='direct', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('received', 'Application Received'), ('screening', 'Under Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='job_fit_score',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='education_weight',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience_weight',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='hard_skills_weight',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills_weight',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='soft_skills_weight',
            field=models.FloatField(default=0.3),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='role_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='job_postings', to='recruitment.jobroleprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='recruitment.skillcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SkillDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('is_hard_skill', models.BooleanField(default=True)),
                ('importance_weight', models.FloatField(default=1.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recruitment.skillcategory')),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_skills', to='recruitment.skilldefinition')),
                ('skill_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.skilltype')),
            ],
        ),
        migrations.CreateModel(
            name='SkillAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias_text', models.CharField(db_index=True, max_length=200)),
                ('normalized_text', models.CharField(db_index=True, max_length=200)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='recruitment.skilldefinition')),
            ],
        ),
        migrations.AddField(
            model_name='jobroleprofile',
            name='preferred_skills',
            field=models.ManyToManyField(blank=True, related_name='preferred_for_roles', to='recruitment.skilldefinition'),
        ),
        migrations.AddField(
            model_name='jobroleprofile',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_for_roles', to='recruitment.skilldefinition'),
        ),
        migrations.CreateModel(
            name='ExtractedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(choices=[('skills', 'Skills'), ('experience', 'Experience'), ('education', 'Education'), ('certifications', 'Certifications'), ('projects', 'Projects'), ('other', 'Other')], max_length=30)),
                ('frequency', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('matched_via', models.CharField(choices=[('exact', 'Exact'), ('alias', 'Alias'), ('fuzzy', 'Fuzzy'), ('nlp', 'NLP')], max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='recruitment.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.skilldefinition')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
