# Generated by Django 5.2.8 on 2025-12-13 22:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_alter_candidate_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESCOOccupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esco_code', models.CharField(max_length=50, unique=True)),
                ('preferred_label', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'ESCO Occupation',
                'verbose_name_plural': 'ESCO Occupations',
            },
        ),
        migrations.RemoveField(
            model_name='jobroleprofile',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='jobroleprofile',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='role_profile',
        ),
        migrations.RemoveField(
            model_name='skillalias',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='skillcategory',
            name='parent',
        ),
        migrations.AlterField(
            model_name='skilldefinition',
            name='category',
            field=models.CharField(choices=[('technical', 'Technical'), ('finance', 'Finance'), ('islamic_finance', 'Islamic Finance'), ('soft_skill', 'Soft Skill'), ('language', 'Language')], default='technical', max_length=20),
        ),
        migrations.RemoveField(
            model_name='skilldefinition',
            name='skill_type',
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={'ordering': ['-created_at'], 'verbose_name': 'Candidate', 'verbose_name_plural': 'Candidates'},
        ),
        migrations.AlterModelOptions(
            name='candidatejobapplication',
            options={'verbose_name': 'Job Application', 'verbose_name_plural': 'Job Applications'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-graduation_year'], 'verbose_name': 'Education', 'verbose_name_plural': 'Education Records'},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'ordering': ['-start_date'], 'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience Records'},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job Posting', 'verbose_name_plural': 'Job Postings'},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={'verbose_name': 'Resume', 'verbose_name_plural': 'Resumes'},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={'ordering': ['-total_score'], 'verbose_name': 'Score', 'verbose_name_plural': 'Scores'},
        ),
        migrations.AlterModelOptions(
            name='skilldefinition',
            options={'verbose_name': 'Skill Definition', 'verbose_name_plural': 'Skill Definitions'},
        ),
        migrations.AlterModelOptions(
            name='workflowevent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Workflow Event', 'verbose_name_plural': 'Workflow Events'},
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='domain_weight',
        ),
        migrations.RemoveField(
            model_name='score',
            name='calculated_at',
        ),
        migrations.RemoveField(
            model_name='skilldefinition',
            name='importance_weight',
        ),
        migrations.RemoveField(
            model_name='skilldefinition',
            name='parent_skill',
        ),
        migrations.AddField(
            model_name='candidate',
            name='years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidatejobapplication',
            name='score_breakdown',
            field=models.JSONField(default=dict, help_text='Detailed scoring breakdown: missing skills, gaps, penalties'),
        ),
        migrations.AddField(
            model_name='candidatejobapplication',
            name='screening_status',
            field=models.CharField(choices=[('PASS', 'Pass - Strong Match'), ('REVIEW', 'Review - Borderline'), ('AUTO_REJECT', 'Auto Reject - Missing Requirements')], default='REVIEW', max_length=20),
        ),
        migrations.AddField(
            model_name='experience',
            name='years',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='created_by',
            field=models.CharField(default='HR Manager', max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='domain',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='islamic_finance_weight',
            field=models.FloatField(default=0.2, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='max_years_experience',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_years_experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='preferred_skills',
            field=models.ManyToManyField(blank=True, related_name='preferred_for_jobs', to='recruitment.skilldefinition'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_certifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_degree',
            field=models.CharField(choices=[('phd', 'PhD'), ('master', 'Master'), ('bachelor', 'Bachelor'), ('none', 'No Degree Required')], default='bachelor', max_length=20),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_for_jobs', to='recruitment.skilldefinition'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='special_requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='score',
            name='evaluated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='score',
            name='rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='skilldefinition',
            name='esco_skill_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_source',
            field=models.CharField(blank=True, choices=[('website', 'Company Website'), ('linkedin', 'LinkedIn'), ('referral', 'Employee Referral'), ('job_board', 'Job Board'), ('direct', 'Direct Application'), ('other', 'Other')], default='direct', max_length=100),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(default=1, max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(choices=[('received', 'Application Received'), ('screening', 'Under Screening'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview Scheduled'), ('offer', 'Offer Extended'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='received', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applications', to='recruitment.candidate'),
        ),
        migrations.AlterField(
            model_name='candidatejobapplication',
            name='job_fit_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='education_weight',
            field=models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience_weight',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='hard_skills_weight',
            field=models.FloatField(default=0.7, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills_weight',
            field=models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='soft_skills_weight',
            field=models.FloatField(default=0.3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='skilldefinition',
            name='canonical_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='esco_occupation',
            field=models.ForeignKey(blank=True, help_text='Link to ESCO occupation for skill normalization', null=True, on_delete=django.db.models.deletion.SET_NULL, to='recruitment.escooccupation'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('proficiency_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='intermediate', max_length=20)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('finance', 'Finance'), ('islamic_finance', 'Islamic Finance'), ('soft_skill', 'Soft Skill'), ('language', 'Language')], default='technical', max_length=20)),
                ('is_hard_skill', models.BooleanField(default=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='recruitment.candidate')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='SkillEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(choices=[('experience', 'Experience'), ('education', 'Education'), ('certification', 'Certification'), ('skills_list', 'Skills List')], max_length=20)),
                ('frequency', models.IntegerField(default=1)),
                ('first_year', models.IntegerField(blank=True, null=True)),
                ('last_year', models.IntegerField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_evidence', to='recruitment.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.skilldefinition')),
            ],
            options={
                'unique_together': {('candidate', 'skill', 'source_section')},
            },
        ),
        migrations.DeleteModel(
            name='ExtractedSkill',
        ),
        migrations.DeleteModel(
            name='JobRoleProfile',
        ),
        migrations.DeleteModel(
            name='SkillAlias',
        ),
        migrations.DeleteModel(
            name='SkillCategory',
        ),
        migrations.DeleteModel(
            name='SkillType',
        ),
    ]
