# Generated by Django 5.2.8 on 2025-12-13 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_escooccupation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='rank',
        ),
    ]
