# Generated by Django 5.2.8 on 2025-12-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0013_remove_score_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='esco_occupation',
        ),
        migrations.RemoveField(
            model_name='skillevidence',
            name='skill',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='preferred_skills',
        ),
        migrations.AlterUniqueTogether(
            name='skillevidence',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='skillevidence',
            name='candidate',
        ),
        migrations.RemoveField(
            model_name='candidatejobapplication',
            name='score_breakdown',
        ),
        migrations.RemoveField(
            model_name='candidatejobapplication',
            name='screening_status',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='domain',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='required_degree',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='min_education_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.DeleteModel(
            name='ESCOOccupation',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='SkillDefinition',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.DeleteModel(
            name='SkillEvidence',
        ),
    ]
