# Generated by Django 5.2.8 on 2025-12-18 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_remove_jobposting_esco_occupation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRoleProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('min_experience', models.IntegerField(default=0)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'recruitment_jobroleprofile',
            },
        ),
        migrations.CreateModel(
            name='SkillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'recruitment_skilltype',
            },
        ),
        migrations.AlterModelOptions(
            name='candidate',
            options={},
        ),
        migrations.AlterModelOptions(
            name='candidatejobapplication',
            options={},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jobposting',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resume',
            options={},
        ),
        migrations.AlterModelOptions(
            name='score',
            options={},
        ),
        migrations.AlterModelOptions(
            name='workflowevent',
            options={},
        ),
        migrations.RenameField(
            model_name='score',
            old_name='evaluated_at',
            new_name='calculated_at',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='islamic_finance_weight',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='max_years_experience',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='min_education_level',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='min_years_experience',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='preferred_skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='required_certifications',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='special_requirements',
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary'), ('other', 'Other')], default='', help_text='Optional. Used for diversity analytics only, not for scoring.', max_length=20),
        ),
        migrations.AddField(
            model_name='candidate',
            name='nationality',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('bahraini', 'Bahraini'), ('gcc', 'GCC National'), ('south_asian', 'South Asian'), ('middle_eastern', 'Middle Eastern'), ('western', 'Western'), ('other', 'Other')], default='', help_text='Optional. Used for diversity analytics only, not for scoring.', max_length=50),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='domain_weight',
            field=models.FloatField(default=0.2),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='application_source',
            field=models.CharField(default='direct', max_length=50),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.CharField(default='received', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='years_experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='field_of_study',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='education_weight',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='experience_weight',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='hard_skills_weight',
            field=models.FloatField(default=0.7),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='skills_weight',
            field=models.FloatField(default=0.25),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='soft_skills_weight',
            field=models.FloatField(default=0.3),
        ),
        migrations.AlterField(
            model_name='score',
            name='education_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='experience_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='islamic_finance_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='skills_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterModelTable(
            name='candidate',
            table='recruitment_candidate',
        ),
        migrations.AlterModelTable(
            name='candidatejobapplication',
            table='recruitment_candidatejobapplication',
        ),
        migrations.AlterModelTable(
            name='education',
            table='recruitment_education',
        ),
        migrations.AlterModelTable(
            name='experience',
            table='recruitment_experience',
        ),
        migrations.AlterModelTable(
            name='jobposting',
            table='recruitment_jobposting',
        ),
        migrations.AlterModelTable(
            name='resume',
            table='recruitment_resume',
        ),
        migrations.AlterModelTable(
            name='score',
            table='recruitment_score',
        ),
        migrations.AlterModelTable(
            name='workflowevent',
            table='recruitment_workflowevent',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='role_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='recruitment.jobroleprofile'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.skillcategory')),
            ],
            options={
                'db_table': 'recruitment_skillcategory',
            },
        ),
        migrations.CreateModel(
            name='SkillDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canonical_name', models.CharField(max_length=200, unique=True)),
                ('is_hard_skill', models.BooleanField(default=True)),
                ('importance_weight', models.FloatField(default=1.0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.skillcategory')),
                ('parent_skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.skilldefinition')),
                ('skill_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruitment.skilltype')),
            ],
            options={
                'db_table': 'recruitment_skilldefinition',
            },
        ),
        migrations.AddField(
            model_name='jobroleprofile',
            name='preferred_skills',
            field=models.ManyToManyField(blank=True, related_name='preferred_for_roles', to='recruitment.skilldefinition'),
        ),
        migrations.AddField(
            model_name='jobroleprofile',
            name='required_skills',
            field=models.ManyToManyField(blank=True, related_name='required_for_roles', to='recruitment.skilldefinition'),
        ),
        migrations.CreateModel(
            name='ExtractedSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_section', models.CharField(max_length=30)),
                ('frequency', models.IntegerField(default=1)),
                ('confidence_score', models.FloatField(default=1.0)),
                ('matched_via', models.CharField(default='exact', max_length=20)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_skills', to='recruitment.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.skilldefinition')),
            ],
            options={
                'db_table': 'recruitment_extractedskill',
                'unique_together': {('candidate', 'skill')},
            },
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
